### ISSUE TITLE
Create a Navbar and add all the components in it as in the UI

### ISSUE THREAD

**Issue by Aman1905** [upskillCommunity/upskill-website#6]

**Comment by astrolover79** [comment]
I would like to do this!

**Comment by Aman1905** [comment]
go on @astrolover79 designs are already in the group

**Comment by Aman1905** [comment]
@astrolover79  navbar is not at all responsive. Make it responsive and remove the shadow from it
add the photo after compressing it (tinyjpeg.com) and do not keep the image in the header folder keep it inside the public folder >image folder

**Comment by astrolover79** [comment]
Ok will do it today
