### ISSUE TITLE
Create the home page fully responsive

### ISSUE THREAD

**Issue by Aman1905** [upskillCommunity/upskill-website#7]

**Comment by Aman1905** [comment]
ok @MdSujan99 do work on it

**Comment by Aman1905** [comment]
@MdSujan99 
1. remove the blue background from home page
2. change font style and size
3. look over the image similar to it on internet and assign it there
4. align the button with the text only not in the center

**Comment by MdSujan99** [comment]
Okay @Aman1905. On it now.

**Comment by MdSujan99** [comment]
I have made these updates and created the pr.

**Comment by Aman1905** [comment]
@MdSujan99 home page is not at all responsive please do the needful asap and make its orientation better,
DO NOT OPEN A PR IN MAIN BRANCH

**Comment by Aman1905** [comment]
Also compress (tinyjpeg.com) the image before adding it and keep that image in the public folder>image folder
and remove all those unnecessary images of the ui from the folder

**Comment by MdSujan99** [comment]
@Aman1905  I think this issue is solved now
